### PR TITLE
Create HelloWorld3

### PR DESCRIPTION
**Pull request by miki164**

### CODE REVIEW

**Comment by rishitsaiya** [comment]
@miki164 Give me a request to review this.

**Comment by miki164** [comment]
How can I do that? Sorry, but I'm very new in contributing to someone else's repositories.

**Comment by rishitsaiya** [comment]
In the top right, u will see this 👇 
Capture
Click on settings and add me to you review your code

**Comment by miki164** [comment]
I tried that, but I don't have settings(geer wheel)
image

**Pull request merged**
